import { createHash } from 'node:crypto';
import { lstat, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { parseOptions, required, writeError, writeLine } from './lib/cli.mjs';
import { candidateEligibility, validateRoutingConfig } from './lib/model-routing.mjs';

const marker = 'Generated by Zimster; managed through .zimster-generated.json';
const { positional, options } = parseOptions(process.argv.slice(2));
const action = positional[0];

function digest(contents) {
  return createHash('sha256').update(contents).digest('hex');
}

async function metadata(target) {
  try { return await lstat(target); } catch (error) { if (error.code === 'ENOENT') return null; throw error; }
}

function safeTarget(root, relative) {
  const target = path.resolve(root, relative);
  if (path.dirname(target) !== root) throw new Error(`generated path escapes explicit output: ${relative}`);
  return target;
}

function candidateForRole(config, role, harness, harnessVersion, catalog, capabilities) {
  const routing = config.routing;
  const capabilityClass = routing.role_classes?.[role];
  const eligible = (capabilityClass ? routing.mappings?.[capabilityClass] || [] : [])
    .map((candidate, index) => ({ candidate, index, eligibility: candidateEligibility(candidate, {
      harness, harnessVersion, catalog, capabilityEvidence: capabilities
    }) }))
    .filter(({ eligibility }) => eligibility.eligible);
  const rank = routing.policy === 'quality_first'
    ? 'quality_rank' : routing.policy === 'cost_optimized' ? 'cost_rank' : 'balanced_rank';
  const candidate = routing.mode === 'map_only'
    ? eligible[0]?.candidate
    : eligible.sort((left, right) => {
      const leftRank = Number.isFinite(left.candidate[rank]) ? left.candidate[rank] : Number.MAX_SAFE_INTEGER;
      const rightRank = Number.isFinite(right.candidate[rank]) ? right.candidate[rank] : Number.MAX_SAFE_INTEGER;
      return leftRank - rightRank || left.index - right.index;
    })[0]?.candidate;
  if (!candidate?.model) throw new Error(`no concrete mapping for role ${role}`);
  return { capabilityClass, candidate };
}

function generatedFile(harness, role, candidate, capabilities) {
  let model = harness === 'opencode' && candidate.provider
    ? `${candidate.provider}/${candidate.model}`
    : candidate.model;
  const effort = candidate.effort || 'inherit';
  if (harness === 'codex') return {
    name: `${role}.toml`,
    contents: `# ${marker}\nmodel = ${JSON.stringify(model)}\nreasoning_effort = ${JSON.stringify(effort)}\n`
  };
  if (harness === 'claude') return {
    name: `${role}.md`,
    contents: `---\nname: ${JSON.stringify(`zimster-${role}`)}\nmodel: ${JSON.stringify(model)}\neffort: ${JSON.stringify(effort)}\n---\n\n<!-- ${marker} -->\nGenerated role override for ${role}.\n`
  };
  if (harness === 'cursor') {
    if (!['native', 'supported_with_constraints'].includes(capabilities.per_agent_model_selection)) {
      throw new Error('Cursor model override requires verified compatible per-agent model fields');
    }
    return {
      name: `${role}.md`,
      contents: `---\nname: ${JSON.stringify(`zimster-${role}`)}\nmodel: ${JSON.stringify(model)}\n---\n\n<!-- ${marker} -->\nGenerated project agent for ${role}. Effective-model reporting may remain unverified.\n`
    };
  }
  if (harness === 'opencode') return {
    name: `${role}.md`,
    contents: `---\ndescription: ${JSON.stringify(`Zimster ${role}`)}\nmode: subagent\nmodel: ${JSON.stringify(model)}\npermission:\n  edit: deny\n---\n\n<!-- ${marker} -->\nGenerated OpenCode agent for ${role}.\n`
  };
  if (harness === 'kimi') {
    if (!['primary', 'secondary'].includes(model)) throw new Error('Kimi mappings may use only primary or secondary');
    if (model === 'secondary' && !['native', 'supported_with_constraints'].includes(capabilities.experimental_secondary_model)) {
      throw new Error('Kimi secondary requires verified experimental secondary-model capability');
    }
    return {
      name: `${role}.json`,
      contents: `${JSON.stringify({ generated_by: 'zimster', role, model }, null, 2)}\n`
    };
  }
  if (harness === 'pi') throw new Error('Pi has no Zimster-managed delegated runtime; use inheritance and owner-inline execution');
  throw new Error(`unsupported harness: ${harness}`);
}

async function generate() {
  const harness = required(options, 'harness').toLowerCase();
  const scope = required(options, 'scope').toLowerCase();
  if (!['project', 'user'].includes(scope)) throw new Error('--scope must be project or user');
  const output = path.resolve(required(options, 'output'));
  const config = validateRoutingConfig(JSON.parse(await readFile(path.resolve(required(options, 'config')), 'utf8')));
  if (config.routing.mode === 'inherit') throw new Error('inherit mode does not generate concrete adapter overrides');
  const catalog = options.catalog
    ? JSON.parse(await readFile(path.resolve(String(options.catalog)), 'utf8'))
    : null;
  const capabilities = options.capabilities
    ? JSON.parse(await readFile(path.resolve(String(options.capabilities)), 'utf8'))
    : {};
  const harnessVersion = String(options['harness-version'] || 'unverified');
  const roles = Object.keys(config.routing.role_classes || {}).sort();
  if (!roles.length) throw new Error('configuration has no routing.role_classes entries');
  await mkdir(output, { recursive: true });
  const outputMetadata = await metadata(output);
  if (outputMetadata?.isSymbolicLink()) throw new Error('output directory must not be a symlink');
  const manifestPath = path.join(output, '.zimster-generated.json');
  const existingManifest = await metadata(manifestPath);
  if (existingManifest?.isSymbolicLink()) throw new Error('generated manifest must not be a symlink');
  let prior = null;
  if (existingManifest) {
    prior = JSON.parse(await readFile(manifestPath, 'utf8'));
    if (prior.owner !== 'zimster' || prior.root !== output || prior.harness !== harness || prior.scope !== scope) {
      throw new Error('refusing incompatible or non-Zimster manifest collision');
    }
  }
  const priorFiles = new Map((prior?.files || []).map((record) => [record.path, record]));
  for (const record of priorFiles.values()) {
    const target = safeTarget(output, record.path);
    const targetMetadata = await metadata(target);
    if (!targetMetadata) continue;
    if (targetMetadata.isSymbolicLink()) throw new Error(`refusing symlink collision: ${target}`);
    if (digest(await readFile(target, 'utf8')) !== record.sha256) {
      throw new Error(`generated file changed since creation: ${target}`);
    }
  }
  const generatedFiles = [];
  for (const role of roles) {
    const { candidate } = candidateForRole(config, role, harness, harnessVersion, catalog, capabilities);
    const generated = generatedFile(harness, role, candidate, capabilities);
    const target = safeTarget(output, generated.name);
    const existingMetadata = await metadata(target);
    if (existingMetadata?.isSymbolicLink()) throw new Error(`refusing symlink collision: ${target}`);
    if (existingMetadata && !priorFiles.has(generated.name)) throw new Error(`refusing user-owned collision: ${target}`);
    generatedFiles.push({ ...generated, target });
  }
  const records = generatedFiles.map((generated) => ({ path: generated.name, sha256: digest(generated.contents) }));
  const manifest = {
    schema_version: 1,
    owner: 'zimster',
    harness,
    scope,
    root: output,
    files: records,
    created_at: new Date().toISOString()
  };
  for (const generated of generatedFiles) await writeFile(generated.target, generated.contents);
  const desired = new Set(records.map(({ path: file }) => file));
  for (const record of priorFiles.values()) {
    if (!desired.has(record.path)) await rm(safeTarget(output, record.path), { force: true });
  }
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  writeLine(manifestPath);
}

async function removeGenerated() {
  const manifestPath = path.resolve(required(options, 'manifest'));
  const manifestMetadata = await metadata(manifestPath);
  if (!manifestMetadata || manifestMetadata.isSymbolicLink()) throw new Error('generated manifest is missing or is a symlink');
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  if (manifest.owner !== 'zimster') throw new Error('manifest is not owned by Zimster');
  const root = path.resolve(manifest.root);
  if (path.dirname(manifestPath) !== root) throw new Error('manifest root mismatch');
  const targets = [];
  for (const record of manifest.files) {
    const target = path.resolve(root, record.path);
    if (path.dirname(target) !== root) throw new Error(`generated path escapes manifest root: ${record.path}`);
    const targetMetadata = await metadata(target);
    if (!targetMetadata) continue;
    if (targetMetadata.isSymbolicLink()) throw new Error(`refusing to remove symlink: ${target}`);
    const contents = await readFile(target, 'utf8');
    if (digest(contents) !== record.sha256) throw new Error(`generated file changed since creation: ${target}`);
    targets.push(target);
  }
  for (const target of targets) await rm(target);
  await rm(manifestPath);
  writeLine(JSON.stringify({ removed: manifest.files.map(({ path: file }) => file), root }));
}

if (action === 'generate') generate().catch(fail);
else if (action === 'remove') removeGenerated().catch(fail);
else fail(new Error('Usage: adapter-config.mjs <generate|remove>'));

function fail(error) {
  writeError(error.message);
  process.exitCode = 1;
}
